security:
    encoders:
        Pronos\AuthBundle\Entity\User:
            algorithm: sha512
            iterations: 6969
            encode_as_base64: true

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_MODERATEUR:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATEUR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
                pattern: ^/
                anonymous: true
                provider: main
                form_login:
                    login_path: fos_user_security_login
                    check_path: fos_user_security_check
                logout: true
                remember_me:
                    key: "%secret%"
                    lifetime: 31536000    # 365 jours en secondes

    access_control:
        - { path: ^/profile/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }