parameters:
#    pronos_pronostics.example.class: Pronos\PronosticsBundle\Example

services:
#    pronos_pronostics.example:
#        class: %pronos_pronostics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
