organization:
    path:     /
    defaults: { _controller: "PronosPronosticsBundle:Organization:index" }

organization_show:
    path:     /{id}/show
    defaults: { _controller: "PronosPronosticsBundle:Organization:show" }

organization_new:
    path:     /new
    defaults: { _controller: "PronosPronosticsBundle:Organization:new" }

organization_create:
    path:     /create
    defaults: { _controller: "PronosPronosticsBundle:Organization:create" }
    methods:  POST

organization_edit:
    path:     /{id}/edit
    defaults: { _controller: "PronosPronosticsBundle:Organization:edit" }

organization_update:
    path:     /{id}/update
    defaults: { _controller: "PronosPronosticsBundle:Organization:update" }
    methods:  [POST, PUT]

organization_delete:
    path:     /{id}/delete
    defaults: { _controller: "PronosPronosticsBundle:Organization:delete" }
    methods:  [POST, DELETE]
