<?php

namespace Pronos\PronosticsBundle\Entity\Repository;

/**
 * DaytimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaytimeRepository extends \Doctrine\ORM\EntityRepository
{
}
