<?php

namespace Pronos\PronosticsBundle\Entity\Repository;

/**
 * PronosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PronosRepository extends \Doctrine\ORM\EntityRepository
{
}
