<?php

namespace Pronos\PronosticsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReglesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglesRepository extends EntityRepository
{
}
